group 'com.amap.flutter.map'
version '1.0'

buildscript {
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.9.0'
    }
}

rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

apply plugin: 'com.android.library'

android {
    namespace = "com.amap.flutter.map"
    compileSdk 35

    defaultConfig {
        minSdk 21
        consumerProguardFiles 'consumer-rules.pro'
//        proguardFiles 'proguard-rules.pro'
    }
    lint {
        disable 'InvalidPackage'
    }
}

dependencies {
    implementation 'com.amap.api:3dmap-location-search:11.2.000_loc11.2.000_sea9.8.0'
    implementation 'androidx.annotation:annotation:1.9.1'
    testImplementation 'junit:junit:4.13.2'
    testImplementation 'org.robolectric:robolectric:4.16'
}
